### ISSUE TITLE
Estimated accuracy of the positions

### ISSUE THREAD

**Issue by ximeng96** [ozheng1993/UCF-SST-CitySim-Dataset#10]
Dear Sir:
I tried to find the estimated accuracy of the position but I could not find it. For example, the researchers claimed that the estimated accuracy of the positions in the highD datasets is 0.1m. 
I wonder what is the estimated accuracy of the positions in the CitySim datasets.
Thank you!

**Comment by ozheng1993** [comment]
Hello Ximen,
Cause we fly at different hight for a different locations, I will say 10-20 cm will be the range.
