### ISSUE TITLE
about trajectory prediction

### ISSUE THREAD

**Issue by jessapinkman** [ozheng1993/UCF-SST-CitySim-Dataset#11]
hey! I appreciate that your work on the transportation open dataset(citysim)，especially task of trajectory prediction. In fact, I have
read your paper called **"Trajectory Prediction for Vehicle Conflict Identification at Intersections Using Sequence-to-Sequence Recurrent Neural Networks"**, and I see that you've already done the work of dealing with raw data, eliminating stationary tracks and dividing the dataset according to 0.7/0.3 respectively. But I cannot find available code anywhere. **I would really appreciate it if you shared your code with me!** And it can also help me avoid doing repetitive work.

**Comment by ozheng1993** [comment]
Hello, you can contact @AmrARaouf about that paper and code
