### ISSUE TITLE
数据集和carla的地图能下载吗？

### ISSUE THREAD

**Issue by Just5D** [ozheng1993/UCF-SST-CitySim-Dataset#4]
现在的下载链接似乎只是样例？非常感谢！

**Comment by ozheng1993** [comment]
Hello, we are planning to release this  full dataset around June

**Comment by feiyuxiaoThu** [comment]
> 现在的下载链接似乎只是样例？非常感谢！

似乎完整数据集需要申请，是否可以保留示例数据供给简单的测试感受，谢谢 @ozheng1993
