### ISSUE TITLE
Freeway B (Basic Segment) data

### ISSUE THREAD

**Issue by 18627242758** [ozheng1993/UCF-SST-CitySim-Dataset#9]
Hello!

Thanks for sharing!

Currently I am using the Freeway B (Basic Segment) data. When plotting the vehicle trajectories using _carCenterXft_ and _carCenterXft_, it is found that in some continuous time steps, X or Y maintains unchanged. For example, the trajectory of vehicle 6268 in FreewayB-01.csv is visualized. You can see there are some horizontal/vertical lines. Could you please help me figure it out?

Thanks.

![image](https://user-images.githubusercontent.com/63514371/208912072-ac8c2f70-b251-4e3a-90ec-4a75ca1385e7.png)

**Comment by ozheng1993** [comment]
Hello!  

I have checked the video, and the freeway B is not a parallel road; there is a certain slope. And we give the raw trajectory data, which will have some vibration from the drone flight. So you will need to apply some smooth functions to this trajectory data. In addition, Your Y axis is from 314 to 324, about 10 feet, but your X is from 1400 to 2400, about 1000 feet; this may magnify this vibration.

Please kindly find an attached snapshot of vehicle 6268.

![Screen Shot 2022-12-23 at 11 08 05 PM](https://user-images.githubusercontent.com/11855659/209420736-938cdfbf-00df-453a-ab4b-2ef4ee1284bf.png)
